name = "flareact-template"
type = "webpack"
account_id = "5d9b28a886b15f78c59376d9fc6b0f8b"
workers_dev = true
route = ""
zone_id = ""
webpack_config = "node_modules/flareact/webpack"

[site]
bucket = "out"
entry-point = "./"
